.github/workflows/ci.yml
Dockerfile

fix Github Actions yaml syntax
we don't need git in the image anymore

fix: Docker setup

---

CMakeLists.txt
Dockerfile
conanfile.txt
include/silo/database.h
src/api.cpp
src/database.cpp
src/main.cpp
src/query_engine/query_engine.cpp

resolves #2 
This is more an MVP than a fully functional solution. It's possible to communicate with SILO via HTTP requests, but:
- handling JSON is quite exhausting in C++. We should think of something how to simplify serializing structs. I didn't find anything premade yet. One always has to build JSON objects by hand. Luckily Poco can serialize those objects into JSON then. #21 
- The interface needs to be hardened: /query should only accept POST requests. If something goes wrong, the application will terminate. #14
- We should not use `assert` as it terminates the application on failure #15
- The current `main.cpp` should be deleted and the relevant content should be migrated to `--processData` of the `api.cpp`. #16
- We should decide what we want to do with the "info_d" command #18 
- …

implement a Rest interface for SILO

---

.dockerignore
.github/workflows/ci.yml
CMakeLists.txt
Dockerfile
README.md
build_with_conan.sh
conanfile.txt
conanprofile.docker
endToEndTests/test/queries/invalidAction.json
endToEndTests/test/queries/invalidMutationsMinProportion.json
endToEndTests/test/queries/nOf_2of3_aggregated.json
endToEndTests/test/queries/nOf_2of3_mutations.json

resolves #12 
previously: ~500 MB, now ~40MB
Also use Conan in the build stage of the Dockerfile and statically link libraries as far as possible. Only TBB strongly advices against statically linking it, so we kept the dynamic link there.

reduce size of Docker images

---

.github/workflows/ci.yml

I didn't manage to make the approach in #31 work, but I found a more reasonable solution: 
* Build a Docker image that contains the tests.
* Execute the unit tests
* Only build the production image if the tests were successful

build: also execute unit tests on pull_request actions

---

.clang-tidy
.gitignore
CMakeLists.txt
Dockerfile
README.md
conanfile.py
include/silo/common/format_number.h
include/silo/database.h
include/silo/prepare_dataset.h
include/silo/query_engine/query_engine.h
include/silo/storage/sequence_store.h
include/silo_api/logging.h
include/silo_api/request_handler.h
src/silo/common/format_number.cpp
src/silo/database.cpp
src/silo/prepare_dataset.cpp
src/silo/query_engine/query_engine.cpp
src/silo/query_engine/query_simplification.cpp
src/silo/storage/sequence_store.cpp
src/silo_api/api.cpp
src/silo_api/logging.cpp
src/silo_api/query_handler.cpp
src/silo_api/request_handler.cpp

This is a part of #19. The performance log statements are not yet migrated to spdlog, they are still written to std::cout. This will be done in a separate step. I would propose to log those log messages into a separate log file.

Use spdlog for logging

---

Dockerfile
Dockerfile_linter

Apply a start period. Maybe this helps that starting the Container doesn't fail on the first try. Also improve caching of the Docker builds by introducing a separate layer that only contains Conan dependencies but none of our code.

build: make healthcheck more robust

---

src/silo/common/nucleotide_symbols.test.cpp
src/silo/common/resolve_alias.test.cpp
src/silo/database.test.cpp
src/silo/preprocessing/preprocessing_exception.test.cpp
src/silo/query_engine/query_engine.cpp
src/silo/storage/position.test.cpp
src/silo_api/variant_json_serializer.test.cpp

Rename the test case names, so they do not contain an underscore. Thus following the guides set by the gtest library
https://github.com/google/googletest/blob/main/docs/faq.md#why-should-test-suite-names-and-test-names-not-contain-underscore

test cases with camel case

---

src/silo/prepare_dataset.cpp
src/silo/query_engine/query_engine.cpp
src/silo/storage/dictionary.cpp

resolves #15
Appreciate early feedback. I propose to solve this via a custom macro in which we can provide a custom error message. Using a macro has the advantage over a function, that we don't need to allocate the error message string if the check does not fail.

fix: throw exceptions instead of terminating the program via the assert macro

---

Dockerfile
docker-compose-for-tests.yml
endToEndTests/test/queries/pangoLIneageIncludingSublineages.json
endToEndTests/test/queries/pangoLIneageWithoutSublineages.json
src/silo/query_engine/query_engine.cpp
src/silo_api/api.cpp

This is prework for https://github.com/GenSpectrum/LAPIS/issues/201
Also listen on port 8081 to avoid conflicts with LAPIS in local setup.

fix: consistently name fields in SILO queries in camel case

---

CMakeLists.txt

Sometimes we observe Docker images that cannot be run in other Github jobs. Very rarely we observe Docker images that cannot be run on our local machines ("Illegal instruction (core dumped)"). Maybe sometimes Github uses different architectures / CPUs in Github Actions? Let's observe whether this change resolves the problems.

build: remove -march=native in CMakeLists.txt

---

README.md
src/silo/common/format_number.cpp
src/silo_api/error_request_handler.cpp

Will resolve #70
More changes should also be included in this PR such as #73 #68.
I will push the changes for #68 after #74 #75, so that I can merge conflicts locally.
I am interested whether the change in `format_numbers.cpp` from including `filesystem` to `sstream` creates any problems for you.

Building for OS X / Mac

---

.github/workflows/ci.yml
Dockerfile
Dockerfile_linter
README.md
conanfile.py
src/silo_api/api.cpp

issue: #92
This makes use of Docker's layer caching. It works as follows:
* layers that don't change are cached and thus not rebuilt.
* For local builds, we also would like to cache Conan's build directories to even further speed up builds there.
* In the images, backup the cached directories (because Docker's bind mounts delete their content after the step) and restore those backups.
* Layers including restoring the backup should be cached, so GitHub Actions should only need to build SILO itself.
Clang tidy still takes very long (~20 minutes). Maybe we can reduce this by refactoring the code into smaller files.

ci: reduce build times by caching Docker layers

---

.github/workflows/cleanUpCaches.yml

See https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#force-deleting-cache-entries
Maybe this improves caching. Caching the Docker images takes quite some space.

ci: delete caches of merged branches

---

Dockerfile_linter
include/silo/config/database_config.h
include/silo/prepare_dataset.h
include/silo/preprocessing/metadata.h
include/silo/preprocessing/pango_lineage_count.h
include/silo/storage/metadata_store.h
src/silo/config/config_repository.cpp
src/silo/config/config_repository.test.cpp
src/silo/config/database_config.cpp
src/silo/config/database_config.test.cpp
src/silo/config/database_config_reader.cpp
src/silo/config/database_config_reader.test.cpp
src/silo/database.cpp
src/silo/prepare_dataset.cpp
src/silo/preprocessing/metadata_validator.test.cpp
src/silo/preprocessing/pango_lineage_count.cpp
src/silo/preprocessing/pango_lineage_count.test.cpp
src/silo/storage/metadata_store.cpp
src/silo/storage/pango_lineage_alias.test.cpp
testBaseData/test_database_config.yaml
testBaseData/test_database_config_with_additional_entries.yaml
testBaseData/test_database_config_with_invalid_metadata_type.yaml
testBaseData/test_database_config_without_date_to_sort_by.yaml

resolves #114 
I think allowing String columns as `partition_by` requires some work, because there is a lot of special logic for pango lineages.

Configure columns

---

.github/workflows/ci.yml

See https://github.com/GenSpectrum/cov-spectrum-website/blob/4331258af55fa25798cd4c073d7190e8588f6ec9/.github/workflows/open_docker.yml#L15-L16
This should fix the red builds on Dependabot PRs.

ci: allow dependabot to push Docker images

---

src/silo/prepare_dataset.cpp
src/silo/preprocessing/metadata.cpp

Currently, the metadata reader crashes with a large file (8 million entries) on ubuntu.
The problem originates from `row[column_name].get<std::string>()` in metadata.cpp . 
This PR fixes the issue in a "hacky" way, since it introduces a small delay, so the memory can be freed. 
The original Error Message
`==98926==ERROR: AddressSanitizer: heap-use-after-free on address 0x6210061860b0 at pc 0x559ad04d84d8 bp 0x7fff3801b380 sp 0x7fff3801b370
READ of size 8 at 0x6210061860b0 thread T0
#0 0x559ad04d84d7 in csv::internals::CSVFieldList::operator[](unsigned long) const /home/kellerer/.conan2/p/vince5ed0da49a4edc/p/include/csv.hpp:7632
#1 0x559ad04d8d18 in csv::CSVRow::get_field(unsigned long) const /home/kellerer/.conan2/p/vince5ed0da49a4edc/p/include/csv.hpp:7691
#2 0x559ad04d851d in …

fix: metadata reader for large files

---

src/silo/common/input_stream_wrapper.cpp

A very small PR with 2 QoL changes.
I lost quite some time debugging, because a file due to experiments, a **folder** was generated that had the name (minus compression extension) of an input file. This was also detected by filesystem::exists. Now we check for actual regular files.
Moreover, a user should also be able to specify compressed files as input, and the InputStreamWrapper should recognise that it already has a .xz or .zst ending, without trying to forcefully append the ending when it wants to read compressed input files.

feat: More robust InputStreamWrapper

---

include/silo/query_engine/actions/aa_mutations.h
include/silo/query_engine/actions/nuc_mutations.h

See https://github.com/GenSpectrum/LAPIS/blob/a5cd5a431a88318ab2593bd6c884960ea8ef1f6a/server/src/main/java/ch/ethz/lapis/api/entity/req/MutationRequest.java#L6

feat: use same default min proportions for mutations actions as LAPIS

---

endToEndTests/test/common.js
endToEndTests/test/info.test.js
endToEndTests/test/query.test.js
include/silo/common/data_version.h
include/silo/database.h
include/silo_api/query_handler.h
src/silo/common/data_version.cpp
src/silo/common/data_version.test.cpp
src/silo/database.cpp
src/silo_api/info_handler.cpp
src/silo_api/query_handler.cpp
src/silo_api/request_handler_factory.cpp
src/silo_api/request_handler_factory.test.cpp

Resolves #130
The data version is returned in the header as `Data-Version` and not `Lapis-Data-Version` as requested in the ticked, since it is the data version from silo. 
This should be reworked, with the verbose preprocessing.

Return the data version

---

include/silo/common/data_version.h
include/silo/config/database_config.h
include/silo/prepare_dataset.h
include/silo/preprocessing/pango_lineage_count.h
include/silo/preprocessing/partition.h
include/silo/preprocessing/preprocessing_config.h
src/silo/common/data_version.cpp
src/silo/config/config_repository.cpp
src/silo/config/database_config.cpp
src/silo/config/database_config.test.cpp
src/silo/database.cpp
src/silo/database.test.cpp
src/silo/prepare_dataset.cpp
src/silo/preprocessing/pango_lineage_count.cpp
src/silo/preprocessing/pango_lineage_count.test.cpp
src/silo/preprocessing/partition.cpp
src/silo/preprocessing/preprocessing_config.cpp
src/silo/preprocessing/preprocessing_config_reader.cpp
testBaseData/test_database_config_without_partition_by.yaml

Not all datasets will contain pango_lineages to partition by for increased compression ratios. Therefore, this PR makes the `partition_by` field optional

feat: make partition_by field in config optional

---

endToEndTests/test/invalidQueries/OffsetNegative.json
endToEndTests/test/queries/DetailsOrderByLimit.json
include/silo/common/string.h
include/silo/query_engine/actions/action.h
include/silo/query_engine/actions/details.h
include/silo/query_engine/actions/tuple.h
include/silo/storage/column_group.h
src/silo/common/string.cpp
src/silo/common/string.test.cpp
src/silo/database.cpp
src/silo/query_engine/actions/aa_mutations.cpp
src/silo/query_engine/actions/action.cpp
src/silo/query_engine/actions/aggregated.cpp
src/silo/query_engine/actions/details.cpp
src/silo/query_engine/actions/fasta_aligned.cpp
src/silo/query_engine/actions/nuc_mutations.cpp
src/silo/query_engine/actions/tuple.cpp
src/silo/query_engine/actions/tuple.test.cpp
src/silo/query_engine/operators/selection.cpp
src/silo/storage/column_group.cpp
src/silo_api/database_directory_watcher.cpp

While Pagination was already possible, the full result still needed to be created first. Now, the details action directly produces sorted data, and only produces as much data as is required. Furthermore this is also multi-threaded

Improve details endpoint

---

endToEndTests/test/queries/aaMutDistribution.json
endToEndTests/test/queries/aaMutDistribution_all.json
endToEndTests/test/queries/aaMutDistribution_multiple.json
endToEndTests/test/queries/nOf_2of3_mutations.json
endToEndTests/test/queries/sequenceStartEndMutations.json
include/silo/query_engine/actions/aa_mutations.h
include/silo/query_engine/actions/nuc_mutations.h
src/silo/query_engine/actions/aa_mutations.cpp
src/silo/query_engine/actions/nuc_mutations.cpp

- to be compatible with lapisv1, which also returns mutation,count,proportion
- name represents the value better, since it has also symbols inside. Positions are only numbers.
This change is necessary for: https://github.com/GenSpectrum/LAPIS/issues/206

refactor: rename "position" in aa_mutations and nuc_mutations to "mutation"

---

CMakeLists.txt
Dockerfile_linter
README.md
build_with_conan.py

feat: do not enforce building with clang-tidy by default. Linter will still be enforced
The Dockerfile_linter has been changed to still enforce clang-tidy

No clang-tidy enforcement by default

---

src/silo/preprocessing/preprocessing_config_reader.cpp

Otherwise the genePrefix would be used for the unalignedNucleotideSequencePrefix

fix: non default unaligned nucleotide sequence prefix

---

endToEndTests/test/info.test.js
include/silo/common/aa_symbols.h
include/silo/common/nucleotide_symbols.h
include/silo/query_engine/actions/mutations.h
include/silo/storage/database_partition.h
include/silo/storage/position.h
include/silo/storage/sequence_store.h
include/silo/zstdfasta/zstdfasta_table_reader.h
src/silo/database.cpp
src/silo/database.test.cpp
src/silo/preprocessing/preprocessor.cpp
src/silo/query_engine/actions/fasta.cpp
src/silo/query_engine/actions/fasta_aligned.cpp
src/silo/query_engine/actions/mutations.cpp
src/silo/query_engine/filter_expressions/aa_symbol_equals.cpp
src/silo/query_engine/filter_expressions/maybe.cpp
src/silo/query_engine/filter_expressions/nucleotide_symbol_equals.cpp
src/silo/query_engine/filter_expressions/or.cpp
src/silo/storage/database_partition.cpp
src/silo/storage/position.cpp
src/silo/storage/position.test.cpp
src/silo/storage/sequence_store.cpp
src/silo/zstdfasta/zstdfasta_table_reader.cpp
src/silo/zstdfasta/zstdfasta_table_reader.test.cpp

The very memory efficient mode is now implemented:
The most numerous bitmap is deleted instead of flipped. When looking up values, all other bitmaps are considered instead.
A good next step would be a hybrid mode, where the deletion is only preferred over flipping, if there is substantial memory gains, as the performance impact is quite high

Optimize bitmaps for more memory-efficiency

---

.clang-tidy
include/silo/common/data_version.h
include/silo/database.h
include/silo/storage/database_partition.h
include/silo/storage/sequence_store.h
include/silo/storage/unaligned_sequence_store.h
src/silo/query_engine/actions/fasta.cpp

Small refactor to always list type members first in the struct and class definitions

refactor: always have type members first in struct

---

endToEndTests/package-lock.json
endToEndTests/package.json
endToEndTests/test/common.js
endToEndTests/test/info.test.js
endToEndTests/test/query.test.js
endToEndTests/test/unknownUrl.test.js

I've tried using the [node test runner](https://nodejs.org/api/test.html) to run the e2e tests, but I'm not sure whether it's worth the trouble. The changes are quite straight forward. There is a small benefit of having on less dependency.

refactor: use node testrunner instead of mocha

---

src/silo/database.cpp

For easier information on the log, whether the database was loaded as expected

feat: display database info after loading new database state

---

include/silo/preprocessing/preprocessing_database.h
include/silo/preprocessing/preprocessor.h
include/silo/preprocessing/sequence_info.h
include/silo/preprocessing/sql_function.h
src/silo/database.test.cpp
src/silo/preprocessing/preprocessing_database.cpp
src/silo/preprocessing/preprocessor.cpp
src/silo/preprocessing/preprocessor.test.cpp
src/silo/preprocessing/sequence_info.cpp
src/silo/preprocessing/sql_function.cpp
src/silo_api/api.cpp

They did not show up in the ci, but if you run the tests locally.

fix: test and address sanatizer after merge of unaligned and sql statements

---

CMakeLists.txt

Currently I need to take out some flags when building for Mac locally, this adds it to the `CMakeLists.txt` and is triggered only for Mac

fix: Make C++ flags in CMake compatible for MacOS

---

README.md

A small fix; `./.run` would be more consistent but I figured too many dots are just confusing, and the `./` is unnecessary for paths that are not executables.

README: fix path

---

.github/workflows/ci.yml
.github/workflows/cleanUpCaches.yml
Dockerfile
Dockerfile_linter

Use a two step approach to build the linter image and the production image. This way we can cache the build of the alpine image and the conan install.

ci: cache linter builder and prod builder in github action

---

include/silo/common/block_timer.h
src/silo/common/block_timer.cpp
src/silo/preprocessing/preprocessor.cpp
src/silo/query_engine/query_engine.cpp

resolves #296
Reading hours displayed in microseconds is not really useful.

feat: display preprocessing duration  in logs in human-readable format

---

src/silo/common/aa_symbols.cpp
src/silo/common/aa_symbols.test.cpp
src/silo/common/nucleotide_symbols.cpp
src/silo/common/nucleotide_symbols.test.cpp
src/silo/test/amino_acid_symbol_equals.test.cpp
src/silo/test/nucleotide_symbol_equals.test.cpp

From https://github.com/GenSpectrum/cov-spectrum-website/issues/938
`'.'` should count if the symbol is equal to the reference genome. This PR should fix that.

fix: nucleotide symbol equals with dot

---

include/silo/query_engine/filter_expressions/symbol_equals.h
src/silo/common/aa_symbols.cpp
src/silo/common/nucleotide_symbols.cpp
src/silo/query_engine/filter_expressions/symbol_equals.cpp

refactor: factorize Dot symbol_equals into named struct instead of abusing std::optional

---

include/silo/database_info.h
src/silo/config/database_config.cpp
src/silo/preprocessing/preprocessing_config.cpp
src/silo/storage/sequence_store.cpp

This broke compatibility with a late 2023 Ubuntu (23.10).

fix: specify namespace fmt in calls to format_to

---

src/silo/query_engine/actions/action.cpp
src/silo/query_engine/actions/fasta.cpp
src/silo/query_engine/actions/fasta_aligned.cpp
src/silo/query_engine/actions/insertions.cpp
src/silo/query_engine/actions/mutations.cpp

related to https://github.com/GenSpectrum/LAPIS/issues/710
Actually one would need to do the same for `Aggregated` and `Details`, too. But this is supposed to be a quick fix and there we have a dynamic list that wasn't that easy to get into an error message.

feat: improve validation error message of some actions on orderByFields

---

src/main.test.cpp
testBaseData/.gitignore

- Ignore directories generated by the preprocessing for tests, and running the test runner
- Make silo_test check that it's running in the project root. While one can deduce the reasons for tests failing by looking at exceptions and drawing the right conclusions, this can easily be overlooked and other people may assume the test has to run from the subdir and run into the same as me.

Testing environment improvements

---

endToEndTests/test/queries/aaMutDistribution.json
endToEndTests/test/queries/aaMutDistribution_all.json
endToEndTests/test/queries/aaMutDistribution_min0.json
endToEndTests/test/queries/aaMutDistribution_multiple.json
endToEndTests/test/queries/aaMutDistribution_very_low.json
endToEndTests/test/queries/nOf_2of3_mutations.json
endToEndTests/test/queries/sequenceStartEndMutations.json
endToEndTests/test/query.test.js
include/silo/query_engine/actions/mutations.h
src/silo/query_engine/actions/mutations.cpp

See https://github.com/loculus-project/loculus/pull/1446

feat: return mutation as object that does not need to be reparsed

---

.github/workflows/ci.yml
Dockerfile
Dockerfile_dependencies
Dockerfile_linter
Dockerfile_linter_dependencies

faster builds by copying [@corneliusroemer](https://github.com/corneliusroemer) image caching for our dependency images, which rarely change

Manual image caching

---

.github/workflows/ci.yml

The current ci only built the arm images on merge to main... but the cache hit check is not platform aware, so it did not rebuild the image for the new platform. Instead of adding a more complicated dependency, also non main ci pipelines will now build ARM *only for the dependency image*.
The good thing, is that this means, that the merge to main then hits the cache and is quicker.

fix: always build dependency image for amd64 platform

---

src/silo/query_engine/actions/mutations.cpp

fix: add missing sequenceName field to mutation action "orderBy"

---

endToEndTests/test/queries/aaInsertionsAction.json
endToEndTests/test/queries/aaInsertionsActionAndFilter.json
endToEndTests/test/queries/aaInsertionsActionOneSequence.json
endToEndTests/test/queries/insertionsAction.json
endToEndTests/test/queries/insertionsActionAndFilter.json
include/silo/query_engine/actions/insertions.h
src/silo/query_engine/actions/insertions.cpp

As discussed in planning this morning. Resolves [bug in LAPIS](https://github.com/GenSpectrum/LAPIS/issues/710) where insertions were not filterable (as they were only added in LAPIS, not already present in SILO)

feat: have structured and destructured insertion in insertions response

---

.dir-locals.el

This adds Emacs configuration specific to this project. Emacs automatically reads this file when editing source files in this repository and indentation settings are then automatically correct.
I don't think this needs documentation, it's used automatically for Emacs users (it asks to confirm using the file on first use), and other users don't care.

add .dir-locals.el for project-specific Emacs settings

---

include/silo_api/runtime_config.h
src/silo_api/api.cpp
src/silo_api/runtime_config.cpp
src/silo_api/runtime_config.test.cpp

feat: tidying up CLI and file configuration for runtime config. Added option for specifying the port
The port on which SILO listens to requests should be able to be specified.
Furthermore, I edited the way the configs are parsed such that there is a default `RuntimeConfig` (default constructor), which has 2 member functions for overwriting its values from 1. the config file and 2. the CLI arguments

Runtime Config

---

endToEndTests/test/queries/floatBetween_noBound.json
src/silo/query_engine/filter_expressions/float_equals.cpp
src/silo/query_engine/operators/selection.cpp
src/silo/test/float_equals_and_between.test.cpp
src/silo/test/int_equals_and_between.test.cpp
src/silo/test/randomize.test.cpp

In https://github.com/GenSpectrum/LAPIS/pull/760 it was found that filtering for null values does not work correctly. This PR targets this issue. The problem was that null is represented as nan in the code. However, equals comparisons with nan always return false. 

fix: floatEquals and floatBetween with null values

---

include/silo/preprocessing/preprocessor.h
include/silo/storage/pango_lineage_alias.h
include/silo/test/query_fixture.test.h
src/silo/database.test.cpp
src/silo/preprocessing/preprocessor.cpp
src/silo/preprocessing/preprocessor.test.cpp
src/silo/query_engine/filter_expressions/pango_lineage_filter.cpp
src/silo/storage/pango_lineage_alias.cpp
src/silo/test/pango_lineage_filter.test.cpp
src/silo_api/api.cpp

In https://github.com/GenSpectrum/LAPIS/pull/760 it was found that filtering for null values does not work correctly. This PR targets this issue. The problem was that null was not allowed for pangolineage filters.

fix: pango lineage filter with null values

---

src/silo/preprocessing/metadata_info.cpp
src/silo/preprocessing/preprocessor.cpp
src/silo/preprocessing/sequence_info.cpp

fix: quoting {} in "x.{}" SQL struct accesses, as a string starting w…
…ith a number leads to parser errors

Fix sequence name quoting

---

Dockerfile

This helps downstream users, e.g. by allowing them to enable dependabot to create update PRs.
See: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file?learn=dependency_version_updates&learnProduct=code-security#docker

chore(ci): Add opencontainers.image.source label

---

endToEndTests/test/info.test.js
include/silo/database_info.h
src/silo/database.cpp
src/silo/database.test.cpp
src/silo_api/info_handler.cpp
src/silo_api/request_handler_factory.test.cpp

Now returns the number of partitions in the info call:
```
{
"nBitmapsSize": 3898,
"numberOfPartitions": 11,
"sequenceCount": 100,
"totalSize": 26589464
}
``` 
- ~~[ ] All necessary documentation has been adapted or there is an issue to do so.~~ (There are no docs for this)

feat: add number of partitions to /info

---

.github/workflows/commitlint.yml

commitlint before only ran when changing the status from draft to ready. The trigger should still contain all types of commits or pr opening, but then only run the job if it is not a draft PR
~- [ ] All necessary documentation has been adapted or there is an issue to do so.~

chore: fixed the commitlint checks to not only run when changing from draft to read_for_review

---

CMakeLists.txt

Creating the .a and then unpacking it again for linking has a high
cost: around 3-3.5 seconds on the server I use: rebuild times when all
source files are in in the ccache drops from 5.5-6.5 to 2.4-2.6
seconds. Rebuild when src/silo/storage/sequence_store.cpp needs
compilation drops from 14.5-15.3 to 11.1-11.8 seconds. Separately
running `ar x ../build/libsilo.a` costs ~0.5 and `ar q my.a *.o` ~1.6
seconds.
We are not making use of libsilo.a, thus remove it.
- ~[] All necessary documentation has been adapted or there is an issue to do so.~
- ~[] The implemented feature is covered by an appropriate test.~

build: do not build intermediary silo library (libsilo.a)

---

CMakeLists.txt

resolves #448
Remove incorrect flags: `set(CMAKE_CXX_FLAGS_RELEASE "[...] -static-libstdc++ -static-libgcc")`
These should instead be declared as
`target_link_options(siloApi PUBLIC  -static-libstdc++ -static-libgcc)`
because `CMAKE_CXX_FLAGS..` are used for the compilation of every unit (.cpp) file. This links standard library code into the output multiple times.
But having that compilation flag is also not desirable, as the tbb's shard object (.so) file is itself linked against shared libgcc and libstdc++ as verified by
```
> ldd libtbb.so
linux-vdso.so.1 (0x00007fffcbca7000)
libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fc3db913000)
libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fc3db8f3000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 …
```

fix: Remove incorrect compile flags

---

testBaseData/numericNames/preprocessing_config.yaml

One can persist the duckdb database that is used during preprocessing for debugging purposes. I didn't remove this option in one of the unit tests. Because the unit tests are run from the repository's root directory, this debug file was also created in that location. This is now removed.

fix: erroneous file created during unit tests should not leak

---

include/silo/common/table_reader.h
src/silo/common/table_reader.cpp

resolves https://github.com/GenSpectrum/cov-spectrum-website/issues/992
SILO was adding insertions at the wrong positions for large input files.

fix: insertions being added at wrong index for large files

---

include/silo/query_engine/query_parse_sequence_name.h
include/silo/test/query_fixture.test.h
src/silo/query_engine/filter_expressions/has_mutation.cpp
src/silo/query_engine/filter_expressions/insertion_contains.cpp
src/silo/query_engine/filter_expressions/symbol_equals.cpp
src/silo/test/amino_acid_insertion_contains.test.cpp
src/silo/test/insertion_contains.test.cpp

Fixes the error, that users could not pass `segmentName: null` or `segmentName: ""` in `insertion_contains` queries. This is necessary for nucleotide insertion queries. https://github.com/GenSpectrum/LAPIS/issues/806 is related to this.
Do we want to treat an empty string the same as passing null? (Currently I have implemented it like it, but we don't have to.
Additionally, we can now test that a query throws an error.

feat: allow null for sequenceName in insertion contains queries

---

src/silo/preprocessing/metadata_info.cpp

resolves issue where SILO occasionally uses a lot more memory for preprocessing since 0.2.3
Before we did a `COUNT(*)` on the entire file, which is costly. Now we do the `COUNT(*)` only on the first row of the file.

fix: more efficient ndjson emptiness check

---

include/silo/common/table_reader.h
include/silo/storage/column_group.h
src/silo/common/table_reader.cpp
src/silo/preprocessing/preprocessor.cpp
src/silo/storage/column_group.cpp

resolves #
instead of the columns pulling the next row from the file_reader, the file_reader
instead pushes the value to the columns using callbacks.
This is in preparation for parallelizing the building of column functions

refactor: lambda-callbacks instead of fill columns

---

include/silo/preprocessing/preprocessor.h
include/silo/preprocessing/sequence_info.h
include/silo/preprocessing/validated_ndjson_file.h
src/silo/preprocessing/preprocessor.cpp
src/silo/preprocessing/sequence_info.cpp
src/silo/preprocessing/sequence_info.test.cpp
src/silo/preprocessing/validated_ndjson_file.cpp

refactor: type safe checking for validation and caching of ndjson-file-emptiness

refactor: type safe checking for validation and caching of ndjson-file-emptiness

---

.github/scripts/preview-changelog.sh
.github/workflows/changelog-preview.yml
package.json

ci: add workflow that comments changelog preview on PRs

---

.github/workflows/ci.yml
.github/workflows/linter.yml
Dockerfile_linter_dependencies

resolves #392 #491 
Now for every pull request the linter is only run on the files, that are changed by the pull request.
We will also add a check for all files again that is run on main and on demand.

make linter only run on changed files 

---

include/silo/common/table_reader.h
src/silo/common/table_reader.cpp
src/silo/preprocessing/preprocessor.cpp

resolves #291
We now use tbb::parallel_for to build the different columns in parallel per input chunk.

Process chunks column-wise in the table reader

---

CMakeLists.txt

Currently two object files are generated for every source file. See the linter doing his work twice:
https://github.com/GenSpectrum/LAPIS-SILO/actions/runs/9599350811/job/26473097915
But also the [normal build step](https://github.com/GenSpectrum/LAPIS-SILO/actions/runs/9599350009/job/26472879416) lists every source file twice, once for each target:
```
#9 367.9 [ 75%] Building CXX object CMakeFiles/siloApi.dir/src/silo/storage/column/date_column.cpp.o
#9 368.8 [ 76%] Building CXX object CMakeFiles/silo_test.dir/src/silo/storage/column/date_column.cpp.o
```
Here cmake is very conservative as different flags could be used to compile the same source file twice.
But we are the ones in control here and can adjust the `CMakeLists.txt` to compile the files once as a library, but without …

build: share library for test and api

---

src/silo/query_engine/actions/action.cpp

resolves #511
I can't quickly add tests for this, as writing them is a large part of the work implementing offset+limit (it needs large dataset, or reducing the cut off via unit tests). Thus the point pushing this fix quickly would be void. I suggest quickly testing this manually instead.

Report limit/offset error

---

include/silo/query_engine/query_parse_exception.h
src/silo/query_engine/actions/action.cpp
src/silo/query_engine/query_parse_exception.cpp
src/silo_api/query_handler.cpp

resolves "also reject sorting" request on Slack.
IIRC we never discussed the further plans for sorting when streaming. Probably refusing with an error ("unimplemented") is really the right thing to do so far. It's a bit weird and potentially problematic in that FASTA/FASTA aligned queries will succeed with sorting first, then when the data set grows until the result set becomes >10'000 rows, they will start to fail. But that may still be better than silently wrong sorting. It would be good to warn the user in advance (while there are still <10'000 rows) somehow; again something that NDJSON cannot deliver, while JSON could contain richer data than just the rows. Documentation will have to be enough, or perhaps the dashboard or other UI components could warn about such queries.
I worry a …

Report sort error

---

Dockerfile
Dockerfile_dependencies

Tests revealed that there is a tremendous difference in speed between alpine and ubuntu images. The 182MB vs 62MB are negligible. 
debian images have a similar memory footprint to ubuntu at 220MB for debian:12 and 178MB for debian:12-slim images

chore: change base image to ubuntu

---

CMakeLists.txt
conanfile.py
endToEndTests/test/invalidQueries/stringSearch_nonExistingColumn.json
endToEndTests/test/invalidQueries/stringSearch_nonStringColumn.json
endToEndTests/test/invalidQueries/stringSearch_withInvalidRegex.json
endToEndTests/test/queries/stringSearch_basic_regex.json
endToEndTests/test/queries/stringSearch_digitAmount.json
endToEndTests/test/queries/stringSearch_justAString.json
endToEndTests/test/queries/stringSearch_prefix.json
endToEndTests/test/query.test.js
include/silo/query_engine/filter_expressions/bool_equals.h
include/silo/query_engine/filter_expressions/date_between.h
include/silo/query_engine/filter_expressions/float_between.h
include/silo/query_engine/filter_expressions/float_equals.h
include/silo/query_engine/filter_expressions/int_between.h
include/silo/query_engine/filter_expressions/int_equals.h
include/silo/query_engine/filter_expressions/pango_lineage_filter.h
include/silo/query_engine/filter_expressions/string_equals.h
include/silo/query_engine/filter_expressions/string_search.h
src/silo/query_engine/filter_expressions/bool_equals.cpp
src/silo/query_engine/filter_expressions/date_between.cpp
src/silo/query_engine/filter_expressions/expression.cpp
src/silo/query_engine/filter_expressions/float_between.cpp
src/silo/query_engine/filter_expressions/float_equals.cpp
src/silo/query_engine/filter_expressions/int_between.cpp
src/silo/query_engine/filter_expressions/int_equals.cpp
src/silo/query_engine/filter_expressions/pango_lineage_filter.cpp
src/silo/query_engine/filter_expressions/string_equals.cpp
src/silo/query_engine/filter_expressions/string_search.cpp

resolves #517 
Introduce a new Filter that filters String fields with regular expressions. Google's RE2 library is used for matching each string value against the user-provided regular expression

feat: new operator for matching strings against regular expressions

---

src/silo/query_engine/actions/fasta.cpp
src/silo/test/fasta.test.cpp

fix: don't abort when unaligned sequence is missing - we should return `null`

---

src/silo/preprocessing/preprocessing_database.cpp

resolves the issue raised in slack of failing GISAID preprocessing on the staging server
duckdb memory_limit was set too conservative. This was done as previous duckdb versions did not conform to the memory limit for all features. This can now be raised to some higher limit.

fix: increase duckdb memory limit to 80GB

---

src/silo/config/preprocessing_config.cpp

resolves #564 
We did not check that either a ndjson or tsv file is actually specified as the input. 
The resulting duckdb error is not parsable for users. Instead we now return a proper error message, also hinting at the possible CLI arguments that can be given instead of amending the preprocessing_config

fix: validate that either a ndjson or tsv file was given as input

---

include/silo/common/panic.h
src/silo/common/panic.cpp
src/silo/common/panic.test.cpp

resolves #559
- ensure that DEBUG_ASSERT's arguments compile: even someone who just compiles in release mode will see if their test expressions in DEBUG_ASSERT(test-expression) compile
- add ASSERT_EQ, ASSERT_LT etc.
- add tests for the important features (including panic features)
I didn't add tests before because I thought it would be necessary to test them (in particular the abort feature) via a script from outside which would have been painful; but turns out gtest has ASSERT_DEATH which allows to do this perfectly.
This PR still doesn't extend UNREACHABLE / UNIMPLEMENTED for arguments, which are a bit challenging to do (the 0-ary case does not need to call fmt::format at all, and CPP macros have no easy dispatch on the number of arguments, but I think I know how to do it anyway now; …

Panic utilities improvements: ensure DEBUG_ASSERT compiles, add ASSERT_EQ etc., add tests

---

include/silo/config/preprocessing_config.h
include/silo/preprocessing/preprocessing_database.h
src/silo/config/preprocessing_config.cpp
src/silo/preprocessing/preprocessing_database.cpp
src/silo/preprocessing/preprocessor.cpp
testBaseData/exampleDatasetAsNdjson/preprocessing_config.yaml

resolves #568 
The memory limit was causing repeated issues as it is handled differently in recent duckdb versions than before. (In theory it is now consistent, but the it only worked smoothly due to inconsistencies in duckdb features that respect the memory limit).

feat: make duckdb memory limit configurable via preprocessing config

---

src/silo/test/string_search.test.cpp

test: add unit tests for `StringSearch` filter

---

src/silo/common/panic.test.cpp

The tests did set the environment variable SILO_PANIC to "" even if it
was "abort", hence debugging e.g. in GDB (when setting that variable
to "abort") didn't work if one of these tests ran before the issue to
debug was triggered.

fix: panic.test: actually revert env var to original value

---

include/silo_api/database_mutex.h
src/silo_api/database_directory_watcher.cpp
src/silo_api/database_mutex.cpp
src/silo_api/info_handler.cpp
src/silo_api/query_handler.cpp
src/silo_api/request_handler_factory.test.cpp

resolves issue mentioned on slack, where the swap-over to the latest folder can sometimes fail.
Before, the setDatabase call requested a write-mutex. This was unnecessarily expensive. Instead, it is enough that we just atomically load and store the current database. Databases lifetimes for currently running transactions is now managed by a shared_ptr, which will correctly deallocate the old state once the last reference to the database is dropped (i.e. the last query using the old state has finished)

fix: prevent setDatabase starvation which leads to no updates of currently loaded database

---

.gitignore

add CLion specific folder cmake-build-release to .gitignore
This folder is generated when building sources in Release mode from CLion

chore: add CLion specific folder cmake-build-release to .gitignore

---

.github/workflows/linter.yml
.gitignore
CMakeLists.txt
Dockerfile
Dockerfile_dependencies
Dockerfile_linter_dependencies
README.md
build_with_conan.py

This follows the convention of putting helper .cmake files in to a separate directory as in: https://cmake.org/cmake/help/latest/variable/CMAKE_MODULE_PATH.html.
This additionally helps with developer setupt. There is now a separate folder (build/) to deleting all generated of the build system (cmake), and a folder (cmake/) of configuration files generated by the package manager (conan)

build: put conan-generated Find<lib>.cmake files in a separate directory from build/

---

CMakeLists.txt
conanfile.py

We depend on fmt transitively through spdlog. Unfortunately, this makes us unable to explicitly depend on a different version of fmt. (There is the newer version 11.0.2 available on conan center, but spdlog still depends on version 10.2.1). With that fmt version there is a bug appearing when using a new version of clang-20. This bug does not appear when not calling the generator for fmt as well.

build: fix broken build for clang by removing erroneous generator for fmt library, which we do not explicitly depend on ourselves

---

CHANGELOG.md

I unfortunately did not do a good job of adding the commit information from the footer in a correct way, such that it will be displayed in the changelog. I now add this manually and improved to the changelog
~- [ ] All necessary documentation has been adapted or there is an issue to do so.~
~- [ ] The implemented feature is covered by an appropriate test.~

doc: update changelog with breaking change information from commit footer

---

CMakeLists.txt
Dockerfile_linter_dependencies

Test PR for now, whether a revert to clang-tidy-15 (using clang-15) will make the CI green again

Linter revert version to clang-15

---

src/silo/preprocessing/metadata_info.cpp

`The field 'versionComment' which is contained in the database config is not contained in the input field '/preprocessing/input/data.ndjson.zst'.` 
looks wrong.

fix(preprocessing): correct error message when field is in config but not in metadata file

---

documentation/lineage_definitions.md

Add documentation for the lineage definitions file, which is required for the specification of monophyletic sublineage queries.

doc: add documentation for the lineage_definitions format

---

README.md
docker-compose-for-tests-preprocessing-from-ndjson.yml

resolves #
improve README.md and remove superfluous database_config mount in the docker compose for ci.
The help text already mentioned that the `database_config` is relative to the input directory.:
```
ConfigAttributeSpecification::createWithDefault(
databaseConfigFileOptionKey(),
ConfigValue::fromPath("database_config.yaml"),
"File name of the file holding the database table configuration. Relative from "
"input_directory."
),
```
Maybe this should have also been in the change-log?

README and docker compose improvement

---

src/silo/query_engine/filter_expressions/int_between.cpp
src/silo/query_engine/filter_expressions/int_equals.cpp
src/silo/test/int_equals_and_between.test.cpp

resolves #636 
The value `INT32_MIN` is currently reserved in an Integer column. This fixes the bug, that a user could still filter for that value and receive unexpected results.

fix: return an error if reserved value INT32_MIN is used in filter

---

.github/workflows/ci.yml

build: only build image for the platform that is currently running in the matrix. Before, both images tried to build and push the production image for both target platforms (`linux/amd64` and `linux/arm64`) on main. The unit tests were always run with the `linux/amd64` image.. For now I changed this to run it for the respective architecture currently running in the matrix. This can be excessive but given that it only runs on main, it might be acceptable?

Fix ci main

---

Dockerfile_dependencies
build_with_conan.py

resolves current CI issue in #666 
The comment in `build_with_conan.py` says all:
We still want to have our dependencies in Release, but the & tells conan we will build the consumer as Debug
Therefore, we set the flag `--settings '&:build_type=Debug'` (in both `build_with_conan.py` and `Dockerfile_dependencies`). 
It was not mentioned in the [docs](https://docs.conan.io/2/reference/commands/install.html), but I found this way of specifying packages only in: 
https://github.com/conan-io/conan/issues/14459

build: correctly specify our conan configuration for Debug builds

---

Dockerfile
Dockerfile_dependencies
conanprofile.docker_arm
include/silo/common/cons_list.h
src/config/config_specification.cpp
src/config/source/environment_variables.cpp
src/silo/common/lineage_tree.cpp
src/silo/config/config_repository.cpp
src/silo/config/database_config.cpp
src/silo/preprocessing/metadata_info.cpp
src/silo/query_engine/actions/tuple.cpp

resolves #663
The base image was still at ubuntu:22.04. Upgrading this gives us access to a newer compiler version

Upgrade base image

---

.github/workflows/ci.yml
Dockerfile

When testing builds, it can be beneficial, to also have the arm images ready to test in PRs. This is not possible currently, because we only build these images on merges main, as github's arm emulation is quite time-consuming. This PR adds the possibility to request an ARM image by adding the label `arm-image` to the PR

Build arm images on demand

---

.github/workflows/ci.yml
Dockerfile_linter

chore: run clang-tidy (linter) on all files when on main or manually triggered

---

.github/workflows/ci.yml
conanfile.py
src/silo/api/api.cpp

There is a [fix](https://github.com/pocoproject/poco/pull/3992) in POCO for a leak in [v1.12.5](https://github.com/pocoproject/poco/blob/poco-1.12.5-release/CHANGELOG). It lead to overallocation of threads during heavy load which are then never deallocated subsequently. This upgrade fixes this leak. It is uncertain, whether it fully resolves the behavior in #697. Therefore, I also introduced an additional change that allocates all threads Poco will ever use already at startup. This makes it easier to profile SILO in the future.

build(deps): update poco dependency version to 1.13.3

---

src/silo/query_engine/actions/fasta.cpp

resolves #697 
While #705 already fixes a memory contention directly, there is another more pressing concern with the download of Fasta sequences. 
Due to the same `malloc` behavior, this leads to an increase of ~1.5 GB every time all mpox sequences are downloaded on Pathoplexus. This is bounded at _some_ point, when malloc decides to finally give back some of its free memory (>90% of the total memory consumption!). This fix tells malloc to trim its memory on every Fasta request.

Hotfix sequence download

---

endToEndTests/test/invalidQueries/insertionContains_invalidPattern.json
endToEndTests/test/invalidQueries/insertionContains_invalidPattern2.json
endToEndTests/test/queries/aaInsertionsAction.json
endToEndTests/test/queries/aaInsertionsActionAndFilter.json
endToEndTests/test/queries/aaInsertionsActionOneSequence.json
endToEndTests/test/queries/insertionContainsStopCodon.json
include/silo/common/aa_symbols.h
include/silo/common/nucleotide_symbols.h
include/silo/storage/insertion_index.h
src/silo/common/aa_symbols.cpp
src/silo/common/aa_symbols.test.cpp
src/silo/common/nucleotide_symbols.cpp
src/silo/common/nucleotide_symbols.test.cpp
src/silo/query_engine/filter/expressions/insertion_contains.cpp
src/silo/storage/insertion_index.cpp

resolves #725
We now correctly expect a `\*` when searching for a stop codon. We validate the insertion search regex to only contain valid symbols, `.*` or `\*`.
Also, clean up of some code paths in the `insertion_index`

fix: correctly expect an escaped stop codon in requests

---

include/silo/api/info_handler.h
include/silo/api/lineage_definition_handler.h
include/silo/api/query_handler.h
src/silo/api/info_handler.cpp
src/silo/api/lineage_definition_handler.cpp
src/silo/api/query_handler.cpp
src/silo/api/request_handler_factory.cpp
src/silo/api/request_handler_factory.test.cpp

resolves #723
We need to delay getting the database into the handlers, otherwise the exception is not caught by the `ErrorRequestHandler`. The `SiloRequestHandlerFactory` must not throw exceptions, because then POCO simply returns an empty response.

fix: return 503 response when no database has been loaded yet

---

include/silo/query_engine/exec_node/legacy_result_producer.h
include/silo/query_engine/exec_node/table_scan.h
src/main.cpp
src/silo/query_engine/actions/fasta_aligned.test.cpp
src/silo/query_engine/exec_node/ndjson_sink.cpp
src/silo/query_engine/exec_node/table_scan.cpp

resolves #777 
There was a bug in `table_scan.cpp` where the method for bulk sequence reconstruction confused the `row_id` in the database with the id in the current batch.

SILO crashes on FastaAligned with InsertionContains filter

---

src/silo/config/preprocessing_config.cpp

resolves a minor issue where a deprecation warning is printed on every execution of `silo preprocessing`
The problem was that the deprecated option `intermediateResultsDirectory` had a default value. When this default value was used on initialization of the config, it printed the deprecation warning

fix: remove erroneous warning printed on every preprocessing run

---

.vscode/extensions.json
src/main.test.cpp

resolves an issue where it is cumbersome to change the working directory where the tests should be run in vscode (see #787). Anyways it should not always require manual setup as also other IDEs use the build directory as the default cwd when running the tests. This is an easy heuristic that should work for most setups

refactor: be more permissible of the working directory when running tests

---

src/silo/storage/column/sequence_column.cpp
src/silo/storage/column/sequence_column.test.cpp

resolves #747
Add validation when adding insertions to the lazy buffer. Not only when building the threemer indexes later

747 insertions validation

---

src/silo/config/runtime_config.cpp

The struct did not initialize the field, therefore it contained random bytes, when no value was given. I talked with Chaoran and we think setting it to 0 by default is best for users. (no need for configuration in e.g. Loculus)

fix: missing initialization of uint32_t in config struct. Set default value in ConfigSpecification instead.

---

endToEndTests/test/invalidQueries/insertionsAAseparation.json
endToEndTests/test/invalidQueries/insertionsInvalidSequence.json
endToEndTests/test/queries/aaInsertionsActionOneSequence.json
endToEndTests/test/queries/insertionsActionAndFilter.json
src/silo/query_engine/actions/insertions.cpp
src/silo/query_engine/actions/insertions.h
src/silo/query_engine/actions/insertions.test.cpp
src/silo/query_engine/actions/mutations.cpp
src/silo/query_engine/actions/mutations.h
src/silo/query_engine/bad_request.h
src/silo/storage/column/float_column.h

resolves #770 
This was very straight-forward with the same approach as for `Mutations`

770 migrate insertions action

---

endToEndTests/test/queries/nOf_2of3_details.json
src/silo/query_engine/actions/action.cpp
src/silo/query_engine/actions/action.h
src/silo/query_engine/actions/aggregated.cpp
src/silo/query_engine/actions/insertions.cpp
src/silo/query_engine/actions/mutations.cpp
src/silo/query_engine/actions/simple_select_action.cpp
src/silo/test/randomize.test.cpp

resolves #794 
This adds back randomization to the arrow query engine. Afterall, I found a solution that did still allow fully featured sorting

feat: add randomize to streaming query engine

---

Makefile
README.md
src/silo/api/api.cpp

In #841, we noticed that SILO did not error, when the port is already in use.
The issue was that Poco's `ServerSocket` constructor and `HTTPServer.start()` don't throw exceptions when the port is already in use - they fail silently. 
Instead explicitly binding the address in `ServerSocket` does throw an exception

Poco throw if port in use

---

benchmarking/.gitignore
benchmarking/Makefile
benchmarking/README.md
benchmarking/bin/build-silo
benchmarking/bin/date-rfc-3339
benchmarking/bin/describe-commit
benchmarking/bin/run-silo
benchmarking/bin/start-silo
benchmarking/bin/stop-silo
benchmarking/evobench-run.ron
src/evobench/_evobench_point_kind.hpp
src/evobench/evobench.cpp
src/evobench/evobench.hpp
src/evobench/evobench_version.hpp
src/silo/api/api.cpp
src/silo/query_engine/filter/expressions/date_between.cpp
src/silo/query_engine/filter/operators/bitmap_producer.cpp
src/silo/query_engine/filter/operators/bitmap_selection.cpp
src/silo/query_engine/filter/operators/complement.cpp
src/silo/query_engine/filter/operators/full.cpp
src/silo/query_engine/filter/operators/index_scan.cpp
src/silo/query_engine/filter/operators/intersection.cpp
src/silo/query_engine/filter/operators/range_selection.cpp
src/silo/query_engine/filter/operators/selection.cpp
src/silo/query_engine/filter/operators/threshold.cpp
src/silo/query_engine/filter/operators/union.cpp
src/silo/query_engine/query_plan.cpp

resolves #757
This adds a copy of the evobench-probes library from [evobench](https://github.com/GenSpectrum/evobench/) as per its documentation (running of `../evobench/evobench-probes/bin/add-include-and-src`), as well as a set of probes (test points).

Benchmarking: add copy of evobench-probes library, and add actual probes

---

src/silo/config/runtime_config.cpp
src/silo/query_engine/actions/aggregated.cpp
src/silo/query_engine/actions/simple_select_action.cpp
src/silo/query_engine/exec_node/ndjson_sink.cpp
src/silo/query_engine/exec_node/table_scan.cpp
src/silo/query_engine/exec_node/table_scan.h
src/silo/query_engine/query_plan.cpp

resolves #862
The problem was that the `StartProducing` method was blocking. This means that while the results were already streamed through the execution plan (which is what I validated manually), the actual http response only started sending after `TableScan::StartProducing` terminated (see `src/silo/query_engine/query_plan.cpp:29` for the precise blocking line).
This means that memory consumption skyrocketed when requesting a large number of sequences. (Up until 1-2 million this was still not too noticable)
This fix makes use of a custom generator object in a generic `SinkNode` instead of rolling our own `TableScan` exec node. This is preferrable, as we do not need to concern ourselves with the following two details:
- Backpressure forwarding: The generic sink node already has …

fix: use arrow::acero::SourceNode when constructing a TableScan

---

benchmarking/Makefile

The resulting data doesn't depend on the data in
WisePulse/target/release/split_into_sorted_chunks--it should not be recreated just because the modification time on that executable changed!
This led to unnecessary CPU investment / latency for jobs.

fix(benchmarking): only depend on WisePulse for running, not the data

---

src/silo/query_engine/actions/action.cpp
src/silo/query_engine/actions/action.h
src/silo/query_engine/actions/aggregated.cpp
src/silo/query_engine/actions/aggregated.h
src/silo/query_engine/actions/aggregated.test.cpp
src/silo/query_engine/actions/details.cpp
src/silo/query_engine/actions/details.test.cpp
src/silo/query_engine/actions/fasta.cpp
src/silo/query_engine/actions/fasta_aligned.cpp
src/silo/query_engine/actions/fasta_aligned.test.cpp
src/silo/test/fasta.test.cpp

resolves #898
We duplicate the `fields`, `sequenceNames`, `additionalFields` and `groupByFields` after parsing them.

fix(silo): correctly deduplicate requested fields

---

benchmarking/Makefile

Also check early for COMMIT_ID.
This will allow to use small (e.g. manually generated) silo_queries.ndjson files and still have enough queries to get reliable results.
Requires a change in etc/evobench-run.ron to add the REPEAT custom variable (with value 50 for compatibility).
Not sure where to document this, if at all.

feat(benchmarking): update api-query, add REPEAT, CONCURRENCY vars

---

benchmarking/Makefile

Pending a more proper new feature in evobench-run (https://github.com/GenSpectrum/evobench/issues/20), this allows us to save the evobench.log file from the preprocessing phase (if it ran).

benchmarking: hack to save the benchmarking output file from the preprocessing phase

---

documentation/phylogenetic_queries.md
endToEndTests/test/invalidQueries/MostRecentCommonAncestor_invalidColumn.json
endToEndTests/test/invalidQueries/Subtree_invalidColumn.json
endToEndTests/test/queries/Subtree_onlyMissingNodes.json
endToEndTests/test/queries/Subtree_simpleQuery.json
endToEndTests/test/queries/Subtree_simple_query_without_unary_nodes.json
endToEndTests/test/queries/Subtree_withMissingNode.json
src/silo/common/phylo_tree.cpp
src/silo/common/phylo_tree.h
src/silo/common/phylo_tree.test.cpp
src/silo/query_engine/actions/action.cpp
src/silo/query_engine/actions/phylo_subtree.cpp
src/silo/query_engine/actions/phylo_subtree.h
src/silo/query_engine/actions/subtree.cpp
src/silo/query_engine/actions/subtree.h
src/silo/query_engine/actions/tree_action.cpp
src/silo/query_engine/actions/tree_action.h
src/silo/storage/column/string_column.h

resolves https://github.com/GenSpectrum/LAPIS-SILO/issues/910, https://github.com/GenSpectrum/LAPIS-SILO/issues/908
2. Adds functions to create a newick from a phylo tree where only nodes in the filter should be seen in the newick
3. Adds tests

feat(silo): add an endpoint to export a newick of the nodes in the filter

---

.github/workflows/ci.yml

This was able to lead releases without images of the released version, as the re-run of the CI on main, which generates the released image, can be cancelled.
In general, CI times have gotten faster and we do not gain anything by cancelling in-progress CI runs

fix(ci): do not cancel in-progress runs

---

benchmarking/Makefile
benchmarking/Makefile_api
benchmarking/Makefile_preprocessing

resolves #919
Allowing for separate benchmarking runs via "make preprocessing" and "make api". The latter still also runs the preprocessing if necessary, but it doesn't collect benchmarking data for it (the evobench probes are disabled by deleting the EVOBENCH_LOG env var). "make preprocessing" however will leave the files around so that a subsequent "make api" can use them, saving a preprocessing run.
Done by splitting off 2 new make files, one per target. That way, each target can do its own checking for required variables (the set of "custom variables" in evobench terminology differs for the two targets), also it keeps them less cluttered. The main "Makefile" is still to be used as entry point, as silo is still built here, and the logic for determining the input file paths is still …

    (benchmarking) feat: add a separate target for the preprocessing

---

src/silo/query_engine/actions/action.cpp
src/silo/query_engine/actions/aggregated.test.cpp
src/silo/query_engine/query_plan.cpp
src/silo/test/query_fixture.test.h

SILO silently crashed requests when a limit was provided without orderByFields in an aggregated query. This fixes that problem and also adds a arrow plan validation before the plan is executed

Bugfix – limit without order

---

CMakeLists.txt

Export compile commands for configuring language servers or debugging the build.
It does have non noticable over-head on project setup

build: always export compile commands

---

endToEndTests/test/invalidQueries/phyloDescendantOf_invalidNode.json
endToEndTests/test/queries/DetailsOrderBy.json
endToEndTests/test/queries/DetailsOrderByLimit.json
endToEndTests/test/queries/LimitLargerThanTable.json
endToEndTests/test/queries/MostRecentCommonAncestor_SimpleQuery.json
endToEndTests/test/queries/MostRecentCommonAncestor_onlyMissingNodes.json
endToEndTests/test/queries/MostRecentCommonAncestor_withMissingNode.json
endToEndTests/test/queries/Offset0.json
endToEndTests/test/queries/OffsetLimitOverlap.json
endToEndTests/test/queries/PhyloDescendantOf.json
endToEndTests/test/queries/Subtree_onlyMissingNodes.json
endToEndTests/test/queries/Subtree_simpleQuery.json
endToEndTests/test/queries/Subtree_simple_query_without_unary_nodes.json
endToEndTests/test/queries/Subtree_withMissingNode.json
endToEndTests/test/queries/nOf_2of3_details.json
src/silo/query_engine/actions/most_recent_common_ancestor.cpp
src/silo/query_engine/actions/most_recent_common_ancestor.h
src/silo/query_engine/actions/phylo_subtree.cpp
src/silo/query_engine/actions/phylo_subtree.h
src/silo/query_engine/actions/tree_action.cpp
src/silo/query_engine/actions/tree_action.h
testBaseData/exampleDataset/README.md
testBaseData/exampleDataset/database_config.yaml

resolves https://github.com/GenSpectrum/LAPIS-SILO/issues/926
1. Adds docs on how the phylogenetic trees were created for the e2e tests.
2. Changes the e2e configuration by adding a new field `usherTree` which should be used as the `phyloTreeField` instead of the primaryKey - the tests had to be modified to now include this new field in the expected result.
3. @chaoran-chen discovered that in the case where there were NULL values in the phyloTree column these are not included in the missing Node count - I have now added these - however, we offer the option to print missing nodes - we print the name of the nodes in the `usherTree` field - thus for NULL values these are not added to the list. Is this intended behavior? Should we create a new field for NULL values instead of adding this to …

feat(silo): include null values in phyloTree column in missingNodeCount

---

src/evobench/evobench.cpp
src/evobench/evobench.hpp
src/silo/query_engine/exec_node/ndjson_sink.cpp

resolves #950
There is a new feature in evobench, described at https://github.com/GenSpectrum/evobench/issues/24#issuecomment-3221833344 ; this updates the copy of the evobench-probes library in SILO to that, and changes the hot probe (mentioned in issue #950, and also described in the linked comment) to be such a new sparse one. This solves the evaluation cost (disk space, RAM use, and benchmarking cpu time), and appears to actually make this probe useful, thus leaving it in in this new form.

Update evobench-probes library, change costly probe to a sparse ('statistical') one

---

src/silo/api/request_handler_factory.test.cpp

resolves locally detected memory leaks when running certain tests

properly free request handlers in tests
