.github/workflows/ci.yml, endToEndTests/.gitignore, endToEndTests/.prettierrc.json, endToEndTests/package-lock.json, endToEndTests/package.json, endToEndTests/test/common.js, endToEndTests/test/info.test.js, endToEndTests/test/unknownUrl.test.js
resolves #22 
This is inspired by [the tests in LAPIS](https://github.com/GenSpectrum/LAPIS/tree/6be322523b64f6fd5ec7b16a0e189f61e4e57ba0/api-tests).
I decided to stay with mocha since it is smaller than jest and we don't need mocks. `/query` cannot yet be meaningfully tested since it does not return proper JSON yet.
=> End To End Tests

.github/workflows/ci.yml, Dockerfile, docker-compose-for-tests.yml
Preparation for https://github.com/GenSpectrum/LAPIS/pull/181.
=> implement Docker health check

endToEndTests/test/queries/invalidAction.json, endToEndTests/test/queries/invalidMutationsMinProportion.json, endToEndTests/test/queries/matchAll.json, endToEndTests/test/queries/nOf_2of3_aggregated.json, endToEndTests/test/queries/nOf_2of3_mutations.json, endToEndTests/test/query.test.js, src/query_engine/query_engine.cpp
used for https://github.com/GenSpectrum/LAPIS/issues/178 for an empty filter
=> feat: add matchAll filter

include/silo/common/log.h, include/silo/query_engine/query_engine.h, src/silo/query_engine/query_engine.cpp, src/silo/query_engine/query_engine_action.cpp, src/silo_api/logging.cpp, src/silo_api/query_handler.cpp
resolves #19
This is a follow up to #51.
=> feat: log performance into a separate file

endToEndTests/test/queries/And.json, endToEndTests/test/queries/Maybe.json, endToEndTests/test/queries/Not.json, endToEndTests/test/queries/Or.json, src/silo/query_engine/query_simplification.cpp
Fix both Or and Maybe expression and add e2e tests. Maybe fix is similar to #91 but without such a nice test :)
=> fix: Or expression and Maybe expression

CMakeLists.txt, conanfile.py, include/silo/config/config_exception.h, include/silo/config/config_repository.h, include/silo/config/database_config.h, include/silo/config/database_config_reader.h, src/silo/config/config_exception.cpp, src/silo/config/config_exception.test.cpp, src/silo/config/config_repository.cpp, src/silo/config/config_repository.test.cpp, src/silo/config/database_config.cpp, src/silo/config/database_config.test.cpp, src/silo/config/database_config_reader.cpp, src/silo/config/database_config_reader.test.cpp, src/silo/preprocessing/preprocessing_exception.test.cpp, testBaseData/test_database_config.yaml, testBaseData/test_database_config_with_additional_entries.yaml, testBaseData/test_database_config_with_invalid_metadata_type.yaml, testBaseData/test_database_config_with_invalid_structure.yaml
Resolves #6
The config is only read. Usage will be implemented with #81 or after.
=> Read the config

include/silo/config/config_repository.h, include/silo/preprocessing/metadata_validator.h, include/silo/preprocessing/preprocessing_config.h, src/silo/config/config_repository.cpp, src/silo/config/config_repository.test.cpp, src/silo/config/database_config_reader.test.cpp, src/silo/database.cpp, src/silo/database.test.cpp, src/silo/preprocessing/metadata_validator.cpp, src/silo/preprocessing/metadata_validator.test.cpp, src/silo/preprocessing/preprocessing_config.cpp, testBaseData/test_database_config.yaml
=> Validate metadata columns against config

endToEndTests/test/queries/intBetween.json, endToEndTests/test/queries/intBetween_noBounds.json, endToEndTests/test/queries/intBetween_openFrom.json, endToEndTests/test/queries/intBetween_openTo.json, endToEndTests/test/queries/intEquals.json, include/silo/config/database_config.h, include/silo/query_engine/filter_expressions/int_between.h, include/silo/query_engine/filter_expressions/int_equals.h, include/silo/storage/column/column.h, include/silo/storage/column/int_column.h, include/silo/storage/metadata_store.h, src/silo/config/database_config.cpp, src/silo/config/database_config.test.cpp, src/silo/config/database_config_reader.test.cpp, src/silo/query_engine/filter_expressions/expression.cpp, src/silo/query_engine/filter_expressions/int_between.cpp, src/silo/query_engine/filter_expressions/int_equals.cpp, src/silo/storage/column/int_column.cpp, src/silo/storage/column/string_column.cpp, src/silo/storage/metadata_store.cpp, testBaseData/small_metadata_set.tsv, testBaseData/test_database_config.yaml
targets #83 - float columns are still missing though.
=> implement Int columns and IntEquals and IntBetween filter

endToEndTests/test/info.test.js, include/silo/common/aa_symbols.h, include/silo/common/nucleotide_symbols.h, include/silo/database.h, include/silo/storage/aa_store.h, include/silo/storage/database_partition.h, include/silo/storage/sequence_store.h, src/silo/common/nucleotide_symbols.test.cpp, src/silo/database.cpp, src/silo/database.test.cpp, src/silo/prepare_dataset.cpp, src/silo/query_engine/actions/nuc_mutations.cpp, src/silo/query_engine/filter_expressions/has_mutation.cpp, src/silo/query_engine/filter_expressions/nucleotide_symbol_equals.cpp, src/silo/storage/aa_store.cpp, src/silo/storage/position.test.cpp, src/silo/storage/sequence_store.cpp
=> feat: amino acids are now stored

include/silo/query_engine/actions/aa_mutations.h, include/silo/query_engine/actions/action.h, include/silo/query_engine/actions/aggregated.h, include/silo/query_engine/actions/details.h, include/silo/query_engine/actions/fasta.h, include/silo/query_engine/actions/fasta_aligned.h, include/silo/query_engine/actions/nuc_mutations.h, src/silo/query_engine/actions/aa_mutations.cpp, src/silo/query_engine/actions/action.cpp, src/silo/query_engine/actions/aggregated.cpp, src/silo/query_engine/actions/details.cpp, src/silo/query_engine/actions/fasta.cpp, src/silo/query_engine/actions/fasta_aligned.cpp, src/silo/query_engine/actions/nuc_mutations.cpp, src/silo/query_engine/query_engine.cpp
Any action just specializes the `execute` and `validateOrderByFields` methods and the action parent class calls these methods and then the order method for all actions.
=> All actions orderableByDefault

src/silo/database.cpp, src/silo/prepare_dataset.cpp, src/silo/preprocessing/partition.cpp, src/silo_api/api.cpp, src/silo_api/logging.cpp
- trace log statements for easier debugging when reading data
- use same fix as in #170 for read in metadata
- add fix that pango_lineages vector is large enough while merging chunks
=> Log statements and small fix to partitioning

.run/silo--api.run.xml, .run/silo--preprocessing.run.xml, README.md
Those proved quite helpful for me.
=> build: persist CLion run config

endToEndTests/test/queries/insertionContains_noSeqCol.json, endToEndTests/test/queries/mutations_False.json, src/silo/query_engine/actions/mutations.cpp
This is a bug-fix which is now covered by 2 additional endToEndTests
CI is failing apparently due to a SourceForge outage: https://github.com/conan-io/conan-center-index/issues/19651
=> Fix mutations

Dockerfile, README.md, src/silo_api/logging.cpp
https://github.com/pathoplexus/pathoplexus/issues/455
=> feat: also log to stdout

endToEndTests/test/queries/detailsLimitAscending5.json, endToEndTests/test/queries/detailsLimitDescending10.json, endToEndTests/test/queries/detailsLimitDescending15.json, src/silo/query_engine/actions/details.cpp
fixes https://github.com/GenSpectrum/LAPIS/issues/572
=> fix: orderBy descending and Limit leading to wrong results

endToEndTests/test/queries/DetailsOrderBy.json, endToEndTests/test/queries/GroupByLineageOrderByCountLimit.json, endToEndTests/test/queries/LimitLargerThanTable.json, endToEndTests/test/queries/Offset0.json, endToEndTests/test/queries/OffsetLimitOverlap.json, endToEndTests/test/queries/PangoLineageAlias.json, include/silo/common/pango_lineage.h, include/silo/common/string_utils.h, include/silo/storage/column/pango_lineage_column.h, include/silo/storage/pango_lineage_alias.h, src/silo/common/bidirectional_map.cpp, src/silo/common/pango_lineage.cpp, src/silo/common/string_utils.cpp, src/silo/common/string_utils.test.cpp, src/silo/query_engine/actions/tuple.cpp, src/silo/storage/column/pango_lineage_column.cpp, src/silo/storage/column/pango_lineage_column.test.cpp, src/silo/storage/column_group.cpp, src/silo/storage/pango_lineage_alias.cpp, src/silo/storage/pango_lineage_alias.test.cpp
=> feat: return only aliased pango lineages

build_with_conan.py
While trying to understand how the build process works, I found this duplication and thought that maybe it will be easier to digest that way. You could also just pick the first of the two commits of course if you prefer that (or feel free to ignore them anyway).
=> Cj build with conan

include/silo_api/error_request_handler.h, src/silo_api/database_directory_watcher.cpp, src/silo_api/error_request_handler.cpp
addressing open comments of https://github.com/GenSpectrum/LAPIS-SILO/pull/299
=> refactor: rename method

endToEndTests/test/requestId.test.js, include/silo_api/request_id_handler.h, src/silo_api/error_request_handler.test.cpp, src/silo_api/logging_request_handler.cpp, src/silo_api/query_handler.cpp, src/silo_api/request_handler_factory.cpp, src/silo_api/request_id_handler.cpp, src/silo_api/request_id_handler.test.cpp
=> feat: implement basic request id to trace requests

src/silo_api/request_id_handler.cpp
=> refactor: don't use an exception when an `if` does the job

.clang-tidy, Dockerfile, Dockerfile_linter, include/silo/database_info.h, src/silo/config/config_repository.test.cpp, src/silo/config/database_config.test.cpp, src/silo/database.cpp, src/silo/preprocessing/metadata_info.test.cpp, src/silo/preprocessing/partition.cpp, src/silo/preprocessing/preprocessing_config_reader.cpp, src/silo/preprocessing/preprocessing_database.cpp, src/silo/preprocessing/preprocessor.test.cpp, src/silo/query_engine/actions/action.cpp, src/silo/query_engine/actions/tuple.cpp, src/silo/storage/column/insertion_column.cpp, src/silo/test/amino_acid_symbol_equals.test.cpp, src/silo/test/date_between.test.cpp, src/silo/test/nucleotide_symbol_equals.test.cpp, src/silo/test/randomize.test.cpp, src/silo_api/api.cpp, src/silo_api/error_request_handler.cpp, src/silo_api/error_request_handler.test.cpp, src/silo_api/not_found_handler.cpp, src/silo_api/query_handler.cpp, src/silo_api/request_handler_factory.test.cpp, src/silo_api/rest_resource.cpp, src/silo_api/variant_json_serializer.test.cpp
=> fix: add bash dependency which is required by conan build of pkgconf and is not installed on alpine by default

.clang-tidy, .dockerignore, .github/workflows/ci.yml, Dockerfile, Dockerfile_linter, conanprofile.docker_arm, include/silo/database_info.h, src/silo/config/config_repository.test.cpp, src/silo/config/database_config.test.cpp, src/silo/database.cpp, src/silo/preprocessing/metadata_info.test.cpp, src/silo/preprocessing/partition.cpp, src/silo/preprocessing/preprocessing_config_reader.cpp, src/silo/preprocessing/preprocessing_database.cpp, src/silo/preprocessing/preprocessor.test.cpp, src/silo/query_engine/actions/action.cpp, src/silo/query_engine/actions/tuple.cpp, src/silo/storage/column/insertion_column.cpp, src/silo/test/amino_acid_symbol_equals.test.cpp, src/silo/test/date_between.test.cpp, src/silo/test/nucleotide_symbol_equals.test.cpp, src/silo/test/randomize.test.cpp, src/silo_api/api.cpp, src/silo_api/error_request_handler.cpp, src/silo_api/error_request_handler.test.cpp, src/silo_api/not_found_handler.cpp, src/silo_api/query_handler.cpp, src/silo_api/request_handler_factory.test.cpp, src/silo_api/rest_resource.cpp, src/silo_api/variant_json_serializer.test.cpp
resolves #302
Building the ARM image takes very long (3 hours), probably since it's using emulation. Doing so on main will suffice. Also on main, the build times don't matter that much.
But it works:
```
$ docker buildx imagetools inspect ghcr.io/genspectrum/lapis-silo@sha256:6aaf2819239cb81129dc5b27ed7a311a8db59b20fa26d576e6a0dfb66d59ee8d
Name:      ghcr.io/genspectrum/lapis-silo@sha256:6aaf2819239cb81129dc5b27ed7a311a8db59b20fa26d576e6a0dfb66d59ee8d
MediaType: application/vnd.oci.image.index.v1+json
Digest:    sha256:6aaf2819239cb81129dc5b27ed7a311a8db59b20fa26d576e6a0dfb66d59ee8d
Manifests: 
Name:        ghcr.io/genspectrum/lapis-silo@sha256:aa806460cc93ddc860be3143edb5c6f64a3bd061e188ef27a26a7ba5c079788f
MediaType:   application/vnd.oci.image.manifest.v1+json
Platform:    linux/amd64 …
```
=> build: publish Docker images for ARM

include/silo/preprocessing/preprocessing_database.h, include/silo/preprocessing/sequence_info.h, include/silo/preprocessing/sql_function.h, include/silo/zstdfasta/zstd_compressor.h, include/silo/zstdfasta/zstd_context.h, include/silo/zstdfasta/zstd_decompressor.h, include/silo/zstdfasta/zstd_dictionary.h, src/silo/preprocessing/preprocessing_database.cpp, src/silo/preprocessing/sequence_info.cpp, src/silo/preprocessing/sql_function.cpp, src/silo/zstdfasta/zstd_compressor.cpp, src/silo/zstdfasta/zstd_context.cpp, src/silo/zstdfasta/zstd_decompressor.cpp, src/silo/zstdfasta/zstd_dictionary.cpp, src/silo/zstdfasta/zstdfasta_table.cpp, src/silo/zstdfasta/zstdfasta_writer.cpp
resolves #282 
Only internal changes. Interface stayed the same in refactor, so tests still cover it
=> Refactor zstd wrappers

include/silo/config/database_config.h, include/silo/query_engine/filter_expressions/int_equals.h, include/silo/query_engine/operators/selection.h, include/silo/storage/column_group.h, src/silo/database.cpp, src/silo/query_engine/operators/operator.cpp, src/silo/storage/column_group.cpp, src/silo_api/api.cpp
Various small issues--cosmetic warnings and safety against code changes.
=> Small fixes

.clang-tidy
=> doc: add message clarifying linter rule disable

conanfile.py, endToEndTests/test/queries/fasta_manySequences.json, endToEndTests/test/queries/nOf_2of3_details.json, include/silo/preprocessing/preprocessing_config.h
=> fix: revert duckdb migration due to it being unable to build the new version on the GitHub runner

endToEndTests/test/queries/complexQuery.json, src/silo/query_engine/filter_expressions/date_between.cpp, src/silo/query_engine/filter_expressions/float_equals.cpp, src/silo/query_engine/filter_expressions/int_between.cpp, src/silo/query_engine/filter_expressions/int_equals.cpp, src/silo/query_engine/filter_expressions/pango_lineage_filter.cpp, src/silo/query_engine/filter_expressions/string_equals.cpp
This fixes error reporting for some kinds of invalid queries.
We ran into this while working on the boolean columns.
Does this warrant tests (I didn't really save the queries we made, sadly, but may be able to reconstruct them)?
=> fix error handling

endToEndTests/test/query.test.js, src/silo_api/query_handler.cpp, src/silo_api/request_handler_factory.test.cpp
BREAKING CHANGE: return data as NDJSON instead of JSON
resolves #126
This is not streaming or anything, but simply iterating over the results and writing them to the output stream one by one.
The error messages are still returned as `application/json`. I think I would leave it that way? Or should we also return error messages as ndjson?
Probably it doesn't make a difference, because the error message is returned as a single-line JSON, which is also valid NDJSON.
=> feat!: return data as NDJSON instead of JSON

.commitlintrc.js, .github/dependabot.yml, .github/workflows/commitlint.yml, .gitignore, README.md, endToEndTests/.gitignore, package-lock.json, package.json
See README.
I don't see the need to enforce a scope here, because this repo essentially has a single artifact (SILO itself).
Related to https://github.com/GenSpectrum/LAPIS/issues/169 and https://github.com/GenSpectrum/dashboards/issues/147
=> build: use commitlint to enforce conventional commits

README.md
=> docs: mention npm run commitlint:merge-base in the README

release-please-config.json
To be merged after the 0.1 release
=> build: only bump patch version for `feat` commit type

.github/dependabot.yml
I'm not 100% sure whether it will update all our Dockerfiles, but let's try.
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates#docker
=> chore: update Docker base images with Dependabot

README.md, package-lock.json, package.json
example: `npm run release-please-dry-run -- --token=ghp_WcVX*****aJkLsg --target-branch=changelogTest`
=> docs: document how to test the changelog that will be generated

Dockerfile_linter_dependencies, src/silo/query_engine/actions/tuple.cpp
Self explanatory, same platform check as in Dockerfile_dependencies
=> chore: make the linter Dockerfile compatible for local arm linting

.github/workflows/ci.yml
otherwise retagging the image fails with "Forbidden"
=> build: grant write permissions to linterDependencies job

include/silo/common/aa_symbols.h, include/silo/common/nucleotide_symbols.h
=> fix: trigger release due to refactor commit-5e3041e5 (#494)

.github/workflows/changelog-preview.yml
=> fix: also trigger when the PR is marked as ready for review

include/silo/common/table_reader.h, include/silo/zstdfasta/zstdfasta_table_reader.h, src/silo/common/table_reader.cpp, src/silo/preprocessing/preprocessor.cpp, src/silo/zstdfasta/zstdfasta_table_reader.cpp
=> Fix the slow preprocessing with more recent releases

src/silo/preprocessing/preprocessor.cpp
In case the directory already exists when running preprocessing, it is manually deleted as the currently used duckdb version does not correctly overwrite the files and may leave duplicate entries in the output
=> fix: manually overwrite already existing unaligned sequence files in the temp folder

CMakeLists.txt, include/silo/common/panic.h, src/silo/common/aa_symbols.cpp, src/silo/common/nucleotide_symbols.cpp, src/silo/common/optional_bool.cpp, src/silo/common/panic.cpp, src/silo/common/string_utils.cpp, src/silo/common/table_reader.cpp, src/silo/database.cpp, src/silo/preprocessing/metadata_info.cpp, src/silo/query_engine/actions/fasta.cpp, src/silo/query_engine/actions/tuple.cpp, src/silo/query_engine/filter_expressions/string_equals.cpp, src/silo/query_engine/filter_expressions/string_search.cpp, src/silo/query_engine/operators/operator.cpp, src/silo/query_engine/operators/selection.cpp, src/silo/storage/column_group.cpp, src/silo/zstd/zstd_decompressor.cpp
resolves #545
I've tested them manually and I hope that's good enough for now.
=> Add ASSERT and more

.github/workflows/changelog-preview.yml
This is copied from the dashboard components, where we have this version already for a while.
=> ci: improve the changelog preview comments

include/silo/storage/column/bool_column.h, include/silo/storage/column/date_column.h, include/silo/storage/column/float_column.h, include/silo/storage/column/indexed_string_column.h, include/silo/storage/column/int_column.h, include/silo/storage/column/string_column.h, src/silo/common/lineage_tree.test.cpp, src/silo/database.cpp, src/silo/query_engine/actions/tuple.cpp, src/silo/query_engine/actions/tuple.test.cpp, src/silo/query_engine/filter_expressions/float_between.cpp, src/silo/query_engine/filter_expressions/float_equals.cpp, src/silo/query_engine/filter_expressions/int_equals.cpp, src/silo/query_engine/filter_expressions/lineage_filter.cpp, src/silo/storage/column/bool_column.cpp, src/silo/storage/column/date_column.cpp, src/silo/storage/column/date_column.test.cpp, src/silo/storage/column/float_column.cpp, src/silo/storage/column/float_column.test.cpp, src/silo/storage/column/indexed_string_column.cpp, src/silo/storage/column/indexed_string_column.test.cpp, src/silo/storage/column/int_column.cpp, src/silo/storage/column/int_column.test.cpp, src/silo/storage/column/string_column.cpp, src/silo/storage/column/string_column.test.cpp, src/silo/storage/column_group.cpp, src/silo_api/request_handler_factory.test.cpp
This code add tests to some column classes that had no unit tests before. Additionally, this adds better error messages for various columns, telling the user more concretely what went wrong.
=> fix: add column_name to column classes and add them to error messages

.gitignore
Ignore .html and test output files when tests stop early.
=> More .gitignore entries

.github/workflows/ci.yml
=> build: fix ci by also adding the platform to the image cache by file hash

.github/workflows/ci.yml
=> build: tell the github runner to explicitly run the unit tests with the image of the platform that is being built

.github/workflows/ci.yml
resolves #682 
Straight-forward removal of the condition checking code
=> build: simplify ci by always building the arm image

src/silo/config/preprocessing_config.cpp
Before, we wrote it in the internal cpp casing `input_directory`..
=> docs: fix help text casing of `inputDirectory`

.dockerignore, .github/workflows/ci.yml, .github/workflows/release.yml, CMakeLists.txt, endToEndTests/test/info.test.js, include/silo/common/version.h, include/silo/database_info.h, src/main.cpp, src/silo/database.cpp, src/silo_api/info_handler.cpp, src/silo_api/request_handler_factory.test.cpp
=>  feat: add the version to the output of the info endpoint

documentation/query_documentation.md, endToEndTests/test/queries/aaInsertionsActionAndFilter.json, endToEndTests/test/queries/aaInsertionsContains.json, endToEndTests/test/queries/insertionContainsStopCodon.json, src/silo/storage/insertion_index.cpp, src/silo/test/default_sequence.test.cpp
=> make InsertionContains match on the full string

endToEndTests/test/queries/detailsLimitAscending5.json, endToEndTests/test/queries/nOf_2of3_details.json, include/silo/query_engine/actions/action.h, include/silo/query_engine/actions/details.h, include/silo/query_engine/exec_node/arrow_util.h, include/silo/query_engine/exec_node/ndjson_sink.h, include/silo/query_engine/query_plan.h, src/silo/query_engine/actions/action.cpp, src/silo/query_engine/actions/details.cpp, src/silo/query_engine/actions/details.test.cpp, src/silo/query_engine/actions/simple_select_action.cpp, src/silo/query_engine/exec_node/ndjson_sink.cpp, src/silo/storage/column_group.cpp, src/silo/test/randomize.test.cpp
resolves #766 
This also migrates the optimized select-k implementation, when sorting is used in conjunction with limit
=> 766 migrate details action to new framework

.github/workflows/formatting.yml, README.md
=> chore(docs): update clang-format and update readme

README.md
=> chore(docs): update lapis docs with instructions how to debug

src/silo/query_engine/actions/action.cpp, src/silo/query_engine/actions/aggregated.cpp, src/silo/query_engine/actions/details.cpp, src/silo/query_engine/actions/fasta.cpp, src/silo/query_engine/actions/fasta_aligned.cpp, src/silo/query_engine/actions/insertions.cpp, src/silo/query_engine/actions/mutations.cpp, src/silo/query_engine/actions/simple_select_action.cpp, src/silo/query_engine/bad_request.h, src/silo/query_engine/filter/expressions/bool_equals.cpp, src/silo/query_engine/filter/expressions/date_between.cpp, src/silo/query_engine/filter/expressions/expression.cpp, src/silo/query_engine/filter/expressions/float_between.cpp, src/silo/query_engine/filter/expressions/float_equals.cpp, src/silo/query_engine/filter/expressions/has_mutation.cpp, src/silo/query_engine/filter/expressions/insertion_contains.cpp, src/silo/query_engine/filter/expressions/int_between.cpp, src/silo/query_engine/filter/expressions/int_equals.cpp, src/silo/query_engine/filter/expressions/lineage_filter.cpp, src/silo/query_engine/filter/expressions/string_equals.cpp, src/silo/query_engine/filter/expressions/string_search.cpp, src/silo/query_engine/filter/expressions/symbol_equals.cpp, src/silo/query_engine/filter/expressions/symbol_equals.h, src/silo/query_engine/query_parse_sequence_name.h
Minor refactor cleaning up a lot of macro usages
=> Check silo query refactor

endToEndTests/test/invalidQueries/insertionsAAseparation.json, endToEndTests/test/invalidQueries/insertionsInvalidSequence.json, endToEndTests/test/queries/aaInsertionsActionOneSequence.json, endToEndTests/test/queries/detailsLimitAscending5.json, endToEndTests/test/queries/insertionsActionAndFilter.json, src/silo/query_engine/actions/action.cpp, src/silo/query_engine/actions/details.test.cpp, src/silo/query_engine/actions/insertions.cpp, src/silo/query_engine/actions/insertions.h, src/silo/query_engine/actions/insertions.test.cpp, src/silo/query_engine/actions/mutations.cpp, src/silo/query_engine/actions/mutations.h, src/silo/query_engine/bad_request.h, src/silo/storage/column/float_column.h
The breaking change to sorting is partly being removed with this PR. Only multi-field sorting is still breaking.
=> Sort order fix

.github/workflows/dependency-image.yml
resolves #825 
This should also make our CI less brittle again, as updates from the conan center index will now automatically make it to the dependency image
=> ci: build a new dependency image daily at 03:00 and tag that image with `latest`

Makefile, README.md
This should help a lot with development, especially for people new to the codebase.
=> build(silo): add Makefile to easily execute ci locally

src/silo/query_engine/exec_node/table_scan.cpp, src/silo/query_engine/exec_node/table_scan.h
=> refactor: use arrow built-in stopped flag

documentation/phylogenetic_queries.md
=> docs: fix indent in JSON example

src/silo/common/phylo_tree.cpp, src/silo/common/phylo_tree.h, src/silo/common/phylo_tree.test.cpp, src/silo/query_engine/actions/most_recent_common_ancestor.cpp, src/silo/query_engine/actions/most_recent_common_ancestor.h, src/silo/query_engine/actions/phylo_subtree.cpp, src/silo/query_engine/actions/phylo_subtree.h, src/silo/query_engine/actions/tree_action.cpp, src/silo/query_engine/actions/tree_action.h
=> feat(silo): further optimizations of queries using the phylo tree - use hash sets instead of vectors

Makefile, documentation/phylogenetic_queries.md, endToEndTests/test/queries/MostRecentCommonAncestor_SimpleQuery.json, endToEndTests/test/queries/MostRecentCommonAncestor_onlyMissingNodes.json, endToEndTests/test/queries/MostRecentCommonAncestor_withMissingNode.json, src/silo/common/phylo_tree.cpp, src/silo/common/phylo_tree.h, src/silo/query_engine/actions/most_recent_common_ancestor.cpp
resolves #924 partly, for a proper generic solution we will design a solution that will allow nested SILO queries
=> Add mrca parent to response

src/silo/query_engine/actions/mutations.cpp, src/silo/storage/column/sequence_column.cpp, src/silo/storage/table.cpp
Could these remain to be useful in the future? It would make it simpler to do my testing if these were in main :)
=> Benchmarking probes for TBB removal work
